### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by dgarner2** [NMan1/Blizard-Account-Generator#4]
can you teach me the steps to use this im having trouble using it

**Comment by NMan1** [comment]
Blizard has changed their login page so this code is outdated

**Comment by dgarner2** [comment]
Any way for you to update it

**Comment by NMan1** [comment]
I can update it, but I probably won't because I don't need it. It wouldn't be difficult for you to do it yourself, if you know python just look up selenium tutorials and that should get you going

**Comment by dgarner2** [comment]
I’m In the process of learning it, I would pay for you to fix it
